language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

install:
  - pip install -r requirements-dev.txt
  - pip install -e .
  - sudo rm -f /etc/mysql/conf.d/performance-schema.cnf
  - sudo service mysql restart

script:
  - ./setup.py test --pytest-args="--cov-report= --cov=mycli"
  - coverage combine
  - coverage report
  - ./setup.py lint

after_success:
  - codecov

notifications:
  webhooks:
    urls:
      - YOUR_WEBHOOK_URL
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
